{% set version = '0.1-2' %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-dtt
  version: {{ version|replace("-", "_") }}

source:
  fn: dtt_{{ version }}.tar.gz
  url:
    - {{ cran_mirror }}/src/contrib/dtt_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/dtt/dtt_{{ version }}.tar.gz
  sha256: b6ee86fb571b3ee04ac1d8d04fbc76b12515c09afee688d56a4f39ea63910f59

build:
  noarch: generic
  merge_build_host: True  # [win]
  number: 1003
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
  host:
    - r-base
  run:
    - r-base

test:
  commands:
    - $R -e "library('dtt')"           # [not win]
    - "\"%R%\" -e \"library('dtt')\""  # [win]

about:
  home: http://www.r-project.org, http://www.komsta.net/
  license: GPL (>= 2)
  summary: This package provides functions for 1D and 2D Discrete Cosine Transform (DCT), Discrete
    Sine Transform (DST) and Discrete Hartley Transform (DHT).
  license_family: GPL3
  license_file: '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3'

extra:
  recipe-maintainers:
    - conda-forge/r
    - CurtLH
