travis:
  secure:
    BINSTAR_TOKEN: IjJLZ7ydAPF+2d6Vgvq+YoD/0Ug73qT2yS7rZ8KD0jcQyjqbl2MF5nO042mZESNPc8t8DR6I4FXO1WokLRtqhgH4EooZuX8RYFc3Ti5jf5Ckn+lIZEP5W5we41IjSP9DvC8GidH83qABE6KxOiiTWy8faiP+ImEuzxlNPJIXxpgItzPJZ0F85KxLYxx9y2qeO8zaE6yd6Oys4cLAufkE8UMRMpaG40+2dtlqTv8sU+PBOkFZ4EE7aWplphDvVtieG1LF6Je8oiUHbLLtgG/A/EzwDjALoICmWq3K0GJIkc7ljOun9nqIBQMUC/34H3+q9YMR9RTefpsC2i8djLgWNj3wl5ufKmtLcyjefGNCBfTmz/XXFF1m6AJvLEyRl3pm/phcb/osXQRGl0q2reRfW4Ci4ygzVZw7yMV+6rCe4rjG96eGhRza+QpB7niFmOPvgHbViULg5YcStKv5dMXyxdczAemn5oRyhVLgbWPaeF6IfoT7FFPhfqNWIgYZeaNkBUPptzdyBS32s0kJ6cQIj0ke6g+MfPEneKFm3xr3yh9V1GeUoSle/PIjQjy30qqSKLGxhVRRyG0e85MncxbW0FqhOVrbdJ3F22aEEWcBBKhZE695vhT0IkptBFi0kAxkKDItJv1HhseBzbH23zAa02q2gGc9m5olcMmHyFytiAc=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
