appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: LicLXujvh9zQ9f0b+QdTkvhzshhYlh5Py2fgRycbW/gGLTPUA5kCPUiwFpw4ICl16kdqWKR9xcw+1Di1FxrUMeZ3CuXaEr9cBoIn3LjCYAKBSAd/9wU2gwFIQ3KsB9ChdxspOQPldsZAP+eV0jdIyL6+OEnxp4mbcmE98KPtZI9d244hiAHhpK4Si+gmnAq2cGDjgxpOLRWFf/0YYZCKz8PNJUN17Oa7aND3my5Mmtx+V8Dtwgdz/Kr3ZeR9cyiTUWAJdPqULt1IomPoFj+qNRxrsmx13ctT4UdzA2waJmbAeKV/a6EOXm1U4RDKpk2maN++Dxz4+PMciks7OMeG7vkJmUydU4RoPXbmObSfjmbFilw3puKCDrauSx1fjwjFXfKLo4GsOi8vMYuSki+qqQ3IXlw1rvAjnGGlyHAcesuO0H6RgOWLlg8IaI2pFtlbvJ4LGulO7BKVnnMQvIyHuL4Fq19weQcNMfg3f3yx59eU+xP8zBbJlONdHmSpYPogpsq5kOnKm0lLGEoKMIOAtBxZ1dQihUENw5UfQssVPHhIh0OB45e5/shwGHU7SjZejsRr3NSLkMZo+OJguGy/rRl6gdwskNoKy7uQzZlV84Igs6bYlZBST4EL80SuOVl/CG4/bNWXL6wExUFfB9Qn79976V/crSw200T9jAZ6QrA=}
